version: 0.2

env:
  variables:
    SPRING_PROFILES_ACTIVE: test # 테스트 프로필 설정
    SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
    SPRING_DATASOURCE_USERNAME: sa
    SPRING_DATASOURCE_PASSWORD:

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Preparing to build..."
      - echo "Setting execute permissions for gradlew..."
      - chmod +x ./gradlew
      - echo "Installing dependencies..."
      - ./gradlew dependencies
  build:
    commands:
      - echo "Building the project..."
      - ./gradlew build -x test
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Running tests..."
      - ./gradlew test
artifacts:
  files:
    - build/libs/sololiving.jar
    - appspec.yml
    - scripts/**

cache:
  paths:
    - /root/.gradle/**/*
