version: 0.2

env:
  variables:
    SPRING_PROFILES_ACTIVE: test

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - chmod +x ./gradlew
      - ./gradlew dependencies

  pre_build:
    commands:
      - echo "Cleaning up old files..."
      - rm -rf /path/to/old/deployments/*
      - echo "Restoring cache..."
      - mkdir -p /codebuild/output/.cache # 캐시 디렉토리를 생성합니다.
      - cp -R /root/.gradle/cache /codebuild/output/.cache/ || true

  build:
    commands:
      - echo "Building the project..."
      - ./gradlew build -x test

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Running tests..."
      - ./gradlew test

      # Gradle 빌드에서 생성된 JAR 파일을 복사합니다.
      - mkdir -p /home/ubuntu/codebuild/output/
      - cp build/libs/*.jar /home/ubuntu/codebuild/output/

      # aws codedeploy 에서 사용될 appspec.yml, scripts 내부 스크립트 파일들 복사
      - cp appspec.yml /home/ubuntu/codebuild/output/
      - cp -R scripts/ /home/ubuntu/codebuild/output/

      # Gradle 캐시를 복사합니다. 해당 경로가 존재하지 않을 경우 에러를 무시합니다.
      - cp -R /home/ubuntu/codebuild/output/.cache /root/.gradle/cache || true

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**

cache:
  paths:
    - /root/.gradle/cache
