version: 0.2

env:
    secrets-manager:
        AWS_ACCESS_KEY_ID: "sololiving-dev/access-key:access-key-id"
        AWS_SECRET_ACCESS_KEY: "sololiving-dev/access-key:access-key"

phases:
    install:
        runtime-versions:
            java: corretto17
        commands:
            - echo "Installing dependencies..."
            - chmod +x ./gradlew
            - ./gradlew dependencies

    pre_build:
        commands:
            - echo "Creating directories for Asciidoctor..."
            - mkdir -p build/generated-snippets
            - mkdir -p src/main/resources/static/docs
            - echo "Cleaning up old files..."
            - rm -rf /path/to/old/deployments/* || true
            - echo "Restoring Gradle cache..."

    build:
        commands:
            - echo "Building the project with tests..."
            - ./gradlew clean build asciidoctor

    post_build:
        commands:
            - echo "Build and tests completed on `date`"
            - echo "Copying build artifacts..."
            - mkdir -p /home/ubuntu/codebuild/output/
            - cp build/libs/*.jar /home/ubuntu/codebuild/output/
            - cp appspec.yml /home/ubuntu/codebuild/output/
            - cp -R scripts/ /home/ubuntu/codebuild/output/
            - echo "Saving Gradle cache..."

artifacts:
    files:
        - build/libs/*.jar
        - appspec.yml
        - scripts/**

cache:
    paths:
        - /root/.gradle/caches
