version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto17
        commands:
            - echo "Installing dependencies..."
            - chmod +x ./gradlew
            - ./gradlew dependencies

    pre_build:
        commands:
            - echo "Creating directories for Asciidoctor..."
            - mkdir -p build/generated-snippets
            - mkdir -p src/main/resources/static/docs
            - echo "Cleaning up old files..."
            - rm -rf /path/to/old/deployments/* || true
            - echo "Restoring cache..."
            - mkdir -p /codebuild/output/.cache
            - cp -R /root/.gradle/cache /codebuild/output/.cache/ || true

    build:
        commands:
            - echo "Building the project..."
            - ./gradlew assemble

    post_build:
        commands:
            - echo "Running tests..."
            - ./gradlew test
            - echo "Tests completed on `date`"
            - echo "Copying build artifacts..."
            - mkdir -p /home/ubuntu/codebuild/output/
            - cp build/libs/*.jar /home/ubuntu/codebuild/output/
            - cp appspec.yml /home/ubuntu/codebuild/output/
            - cp -R scripts/ /home/ubuntu/codebuild/output/
            - echo "Saving Gradle cache..."
            - cp -R /home/ubuntu/codebuild/output/.cache /root/.gradle/cache || true

artifacts:
    files:
        - build/libs/*.jar
        - appspec.yml
        - scripts/**

cache:
    paths:
        - /root/.gradle/cache
